flow_map = {
    "account_access": "Account Access",
    "manage_account": "Manage Account",
    "order_issue": "Order Issue",
    "product_defect": "Product Defect",
    "purchase_dispute": "Purchase Dispute",
    "shipping_issue": "Shipping Issue",
    "single_item_query": "Single-Item Query",
    "storewide_query": "Storewide Query",
    "subscription_inquiry": "Subscription Inquiry",
    "troubleshoot_site": "Troubleshoot Site",
}

subflow_map = {
    "recover_username": "Recover Username",
    "recover_password": "Recover Password",
    "reset_2fa": "Reset Two-Factor Auth",
    "status_service_added": "Status Service Added",
    "status_service_removed": "Status Service Removed",
    "status_shipping_question": "Status Shipping Question",
    "status_credit_missing": "Status Credit Missing",
    "manage_change_address": "Manage Change Address",
    "manage_change_name": "Manage Change Name",
    "manage_change_phone": "Manage Change Phone",
    "manage_payment_method": "Manage Payment Method",
    "status_mystery_fee": "Status Mystery Fee",
    "status_delivery_time": "Status Delivery Time",
    "status_payment_method": "Status Payment Method",
    "status_quantity": "Status Quantity",
    "manage_upgrade": "Manage Upgrade",
    "manage_downgrade": "Manage Downgrade",
    "manage_create": "Manage Create",
    "manage_cancel": "Manage Cancel",
    "refund_initiate": "Initiate Refund",
    "refund_update": "Update Refund",
    "refund_status": "Refund Status",
    "return_stain": "Return Due to Stain",
    "return_color": "Return Due to Color",
    "return_size": "Return Due to Size",
    "bad_price_competitor": "Bad Price Competitor",
    "bad_price_yesterday": "Bad Price Yesterday",
    "out_of_stock_general": "Out-of-Stock General",
    "out_of_stock_one_item": "Out-of-Stock One Item",
    "promo_code_invalid": "Promo Code Invalid",
    "promo_code_out_of_date": "Promo Code Out of Date",
    "mistimed_billing_already_returned": "Mistimed Billing Already Returned",
    "mistimed_billing_never_bought": "Mistimed Billing Never Bought",
    "status": "Shipping Status",
    "manage": "Manage Shipping",
    "missing": "Missing Item",
    "cost": "Shipping Cost",
    "boots": "Boots FAQ",
    "shirt": "Shirt FAQ",
    "jeans": "Jeans FAQ",
    "jacket": "Jacket FAQ",
    "pricing": "Pricing FAQ",
    "membership": "Membership FAQ",
    "timing": "Timing FAQ",
    "policy": "Policy FAQ",
    "status_active": "Status Active",
    "status_due_amount": "Status Due Amount",
    "status_due_date": "Status Due Date",
    "manage_pay_bill": "Manage Pay Bill",
    "manage_extension": "Manage Extension",
    "manage_dispute_bill": "Manage Dispute Bill",
    "credit_card": "Invalid Credit Card",
    "shopping_cart": "Cart Not Updating",
    "search_results": "Search Not Working",
    "slow_speed": "Website Too Slow",
}

